"""copy on link question templates

Revision ID: 272290b41af4
Revises: ac775b2924f1
Create Date: 2026-03-19 13:59:32.253061

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "272290b41af4"
down_revision: str | Sequence[str] | None = "ac775b2924f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_question_template_bank_question_templates_question_t_49f6"),
        table_name="question_template_bank_question_templates",
    )
    op.drop_index(
        op.f("ix_question_template_bank_question_templates_question_t_6055"),
        table_name="question_template_bank_question_templates",
    )
    op.drop_table("question_template_bank_question_templates")
    op.drop_index(
        op.f("ix_assessment_template_question_templates_assessment_te_1b06"),
        table_name="assessment_template_question_templates",
    )
    op.drop_index(
        op.f("ix_assessment_template_question_templates_question_template_id"),
        table_name="assessment_template_question_templates",
    )
    op.drop_table("assessment_template_question_templates")
    op.add_column(
        "question_templates",
        sa.Column("assessment_template_id", sa.Uuid(), nullable=True),
    )
    op.add_column(
        "question_templates",
        sa.Column("question_template_bank_id", sa.Uuid(), nullable=True),
    )
    op.add_column(
        "question_templates",
        sa.Column("linked_from_template_id", sa.Uuid(), nullable=True),
    )
    op.add_column("question_templates", sa.Column("order", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_question_templates_assessment_template_id"),
        "question_templates",
        ["assessment_template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_templates_linked_from_template_id"),
        "question_templates",
        ["linked_from_template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_templates_question_template_bank_id"),
        "question_templates",
        ["question_template_bank_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_question_template_assessment_template_order",
        "question_templates",
        ["assessment_template_id", "order"],
    )
    op.create_check_constraint(
        "ck_question_template_single_container",
        "question_templates",
        "assessment_template_id IS NULL OR question_template_bank_id IS NULL",
    )
    op.create_foreign_key(
        "fk_question_templates_question_template_bank_id",
        "question_templates",
        "question_template_banks",
        ["question_template_bank_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_question_templates_linked_from_template_id",
        "question_templates",
        "question_templates",
        ["linked_from_template_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_question_templates_assessment_template_id",
        "question_templates",
        "assessment_templates",
        ["assessment_template_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_question_templates_assessment_template_id",
        "question_templates",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_question_templates_linked_from_template_id",
        "question_templates",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_question_templates_question_template_bank_id",
        "question_templates",
        type_="foreignkey",
    )
    op.drop_constraint(
        "ck_question_template_single_container", "question_templates", type_="check"
    )
    op.drop_constraint(
        "uq_question_template_assessment_template_order",
        "question_templates",
        type_="unique",
    )
    op.drop_index(
        op.f("ix_question_templates_question_template_bank_id"),
        table_name="question_templates",
    )
    op.drop_index(
        op.f("ix_question_templates_linked_from_template_id"),
        table_name="question_templates",
    )
    op.drop_index(
        op.f("ix_question_templates_assessment_template_id"),
        table_name="question_templates",
    )
    op.drop_column("question_templates", "order")
    op.drop_column("question_templates", "linked_from_template_id")
    op.drop_column("question_templates", "question_template_bank_id")
    op.drop_column("question_templates", "assessment_template_id")
    op.create_table(
        "assessment_template_question_templates",
        sa.Column(
            "assessment_template_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "question_template_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column("order", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "added_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_template_id"],
            ["assessment_templates.id"],
            name=op.f(
                "assessment_template_question_templa_assessment_template_id_fkey"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_template_id"],
            ["question_templates.id"],
            name=op.f(
                "assessment_template_question_template_question_template_id_fkey"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("assessment_template_question_templates_pkey")
        ),
        sa.UniqueConstraint(
            "assessment_template_id",
            "order",
            name=op.f("uq_assessment_template_question_template_order"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "assessment_template_id",
            "question_template_id",
            name=op.f("uq_assessment_template_question_template"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_assessment_template_question_templates_question_template_id"),
        "assessment_template_question_templates",
        ["question_template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_template_question_templates_assessment_te_1b06"),
        "assessment_template_question_templates",
        ["assessment_template_id"],
        unique=False,
    )
    op.create_table(
        "question_template_bank_question_templates",
        sa.Column(
            "question_template_bank_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "question_template_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "added_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_template_bank_id"],
            ["question_template_banks.id"],
            name=op.f(
                "question_template_bank_question__question_template_bank_id_fkey"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_template_id"],
            ["question_templates.id"],
            name=op.f(
                "question_template_bank_question_templ_question_template_id_fkey"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("question_template_bank_question_templates_pkey")
        ),
        sa.UniqueConstraint(
            "question_template_bank_id",
            "question_template_id",
            name=op.f("uq_question_template_bank_question_template"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_question_template_bank_question_templates_question_t_6055"),
        "question_template_bank_question_templates",
        ["question_template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_template_bank_question_templates_question_t_49f6"),
        "question_template_bank_question_templates",
        ["question_template_bank_id"],
        unique=False,
    )
    # ### end Alembic commands ###
