"""defer order checks and add enum for question type

Revision ID: 2995b8d71450
Revises: a6ed89ae3130
Create Date: 2026-05-04 11:52:35.737316

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2995b8d71450"
down_revision: str | Sequence[str] | None = "a6ed89ae3130"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        """
        ALTER TABLE questions
        ALTER COLUMN question_type
        TYPE question_type
        USING question_type::text::question_type
        """
    )

    op.drop_constraint(
        constraint_name="uq_question_assessment_order",
        table_name="questions",
    )

    op.create_unique_constraint(
        constraint_name="uq_question_assessment_order",
        table_name="questions",
        columns=["assessment_id", "order"],
        deferrable=True,
        initially="DEFERRED",
    )

    op.drop_constraint(
        constraint_name="uq_question_template_assessment_template_order",
        table_name="question_templates",
    )

    op.create_unique_constraint(
        constraint_name="uq_question_template_assessment_template_order",
        table_name="question_templates",
        columns=["assessment_template_id", "order"],
        deferrable=True,
        initially="DEFERRED",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "questions",
        "question_type",
        existing_type=sa.Enum("mcq", "mrq", "short_answer", name="question_type"),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###

    op.drop_constraint(
        constraint_name="uq_question_assessment_order",
        table_name="questions",
    )

    op.create_unique_constraint(
        constraint_name="uq_question_assessment_order",
        table_name="questions",
        columns=["assessment_id", "order"],
    )

    op.drop_constraint(
        constraint_name="uq_question_template_assessment_template_order",
        table_name="question_templates",
    )

    op.create_unique_constraint(
        constraint_name="uq_question_template_assessment_template_order",
        table_name="question_templates",
        columns=["assessment_template_id", "order"],
    )
