"""add question template bank

Revision ID: 2e9d66c17dc1
Revises: ca836cc22081
Create Date: 2026-02-15 13:04:40.542683

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e9d66c17dc1"
down_revision: str | Sequence[str] | None = "ca836cc22081"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_template_banks",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("folder_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["folder_id"], ["folders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_template_banks_folder_id"),
        "question_template_banks",
        ["folder_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_template_banks_owner_id"),
        "question_template_banks",
        ["owner_id"],
        unique=False,
    )
    op.create_table(
        "question_template_bank_question_templates",
        sa.Column("question_template_bank_id", sa.Uuid(), nullable=False),
        sa.Column("question_template_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["question_template_bank_id"], ["question_template_banks.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["question_template_id"], ["question_templates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "question_template_bank_id",
            "question_template_id",
            name="uq_question_template_bank_question_template",
        ),
    )
    op.create_index(
        op.f("ix_question_template_bank_question_templates_question_template_bank_id"),
        "question_template_bank_question_templates",
        ["question_template_bank_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_template_bank_question_templates_question_template_id"),
        "question_template_bank_question_templates",
        ["question_template_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_question_template_bank_question_templates_question_template_id"),
        table_name="question_template_bank_question_templates",
    )
    op.drop_index(
        op.f("ix_question_template_bank_question_templates_question_template_bank_id"),
        table_name="question_template_bank_question_templates",
    )
    op.drop_table("question_template_bank_question_templates")
    op.drop_index(op.f("ix_question_template_banks_owner_id"), table_name="question_template_banks")
    op.drop_index(
        op.f("ix_question_template_banks_folder_id"), table_name="question_template_banks"
    )
    op.drop_table("question_template_banks")
    # ### end Alembic commands ###
