"""add collab to other resources

Revision ID: 586b9870870f
Revises: 272290b41af4
Create Date: 2026-03-22 15:40:13.706590

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "586b9870870f"
down_revision: str | Sequence[str] | None = "272290b41af4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assessment_templates", sa.Column("visibility", sa.String(length=50), nullable=False)
    )
    op.alter_column("assessment_templates", "description", existing_type=sa.TEXT(), nullable=False)
    op.add_column("question_banks", sa.Column("visibility", sa.String(length=50), nullable=False))
    op.add_column(
        "question_template_banks", sa.Column("visibility", sa.String(length=50), nullable=False)
    )
    op.alter_column(
        "question_template_banks", "description", existing_type=sa.TEXT(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "question_template_banks", "description", existing_type=sa.TEXT(), nullable=True
    )
    op.drop_column("question_template_banks", "visibility")
    op.drop_column("question_banks", "visibility")
    op.alter_column("assessment_templates", "description", existing_type=sa.TEXT(), nullable=True)
    op.drop_column("assessment_templates", "visibility")
    # ### end Alembic commands ###
