"""add question text template

Revision ID: 5bd365832755
Revises: 8bea5bfceb27
Create Date: 2026-03-08 14:22:05.880487

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5bd365832755"
down_revision: str | Sequence[str] | None = "8bea5bfceb27"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE text_template_type AS ENUM ('basic', 'mustache')")

    op.add_column(
        "question_templates", sa.Column("question_text_template", sa.Text(), nullable=False)
    )
    op.add_column(
        "question_templates",
        sa.Column(
            "text_template_type",
            sa.Enum("basic", "mustache", name="text_template_type"),
            nullable=False,
        ),
    )
    op.drop_column("question_templates", "question_text")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question_templates",
        sa.Column("question_text", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_column("question_templates", "text_template_type")
    op.drop_column("question_templates", "question_text_template")

    op.execute("DROP TYPE IF EXISTS text_template_type")
    # ### end Alembic commands ###
