"""refactor template config to structured fields

Revision ID: 79dc1a47e5c6
Revises: c31d5bcd841c
Create Date: 2026-02-13 14:52:17.130809

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79dc1a47e5c6"
down_revision: str | Sequence[str] | None = "c31d5bcd841c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE output_type AS ENUM ('list', 'count', 'first', 'last')")
    op.execute("CREATE TYPE question_type AS ENUM ('mcq', 'mrq', 'short_answer')")

    op.create_table(
        "target_elements",
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column(
            "element_type",
            sa.Enum("function", "loop", "branch", "variable", name="target_element_type"),
            nullable=False,
        ),
        sa.Column("id_list", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column(
            "modifier",
            sa.Enum(
                "arguments",
                "return_value",
                "loop_iterations",
                "branch_true",
                "branch_false",
                name="target_modifier",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["template_id"], ["question_templates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("template_id", "order"),
    )
    op.add_column("question_templates", sa.Column("code", sa.Text(), nullable=False))
    op.add_column(
        "question_templates", sa.Column("entry_function", sa.String(length=255), nullable=False)
    )
    op.add_column("question_templates", sa.Column("num_distractors", sa.Integer(), nullable=False))
    op.add_column(
        "question_templates",
        sa.Column(
            "output_type",
            sa.Enum("list", "count", "first", "last", name="output_type"),
            nullable=False,
        ),
    )
    op.alter_column(
        "question_templates",
        "question_type",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum("mcq", "mrq", "short_answer", name="question_type"),
        existing_nullable=False,
        postgresql_using="question_type::question_type",
    )
    op.drop_column("question_templates", "template_config")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question_templates",
        sa.Column(
            "template_config",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "question_templates",
        "question_type",
        existing_type=sa.Enum("mcq", "mrq", "short_answer", name="question_type"),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_column("question_templates", "output_type")
    op.drop_column("question_templates", "num_distractors")
    op.drop_column("question_templates", "entry_function")
    op.drop_column("question_templates", "code")
    op.drop_table("target_elements")

    op.execute("DROP TYPE IF EXISTS output_type")
    op.execute("DROP TYPE IF EXISTS question_type")
    op.execute("DROP TYPE IF EXISTS target_element_type")
    op.execute("DROP TYPE IF EXISTS target_modifier")
    # ### end Alembic commands ###
