"""add resource collaborators

Revision ID: 8a6af857e1df
Revises: fef2e085b62e
Create Date: 2026-03-16 20:10:59.311375

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a6af857e1df"
down_revision: str | Sequence[str] | None = "fef2e085b62e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resource_collaborators",
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "resource_type", "resource_id", "user_id", name="uq_resource_collaborator"
        ),
    )
    op.create_index(
        "ix_resource_collaborators_type_resource",
        "resource_collaborators",
        ["resource_type", "resource_id"],
        unique=False,
    )
    op.create_index(
        "ix_resource_collaborators_user_id", "resource_collaborators", ["user_id"], unique=False
    )
    # ### end Alembic commands ###

    # Backfill owner rows for all existing non-deleted assessments
    op.execute("""
        INSERT INTO resource_collaborators (id, resource_type, resource_id, user_id, role, added_at)
        SELECT gen_random_uuid(), 'assessment', id, owner_id, 'owner', created_at
        FROM assessments
        WHERE deleted_at IS NULL
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_resource_collaborators_user_id", table_name="resource_collaborators")
    op.drop_index("ix_resource_collaborators_type_resource", table_name="resource_collaborators")
    op.drop_table("resource_collaborators")
    # ### end Alembic commands ###
