"""add assessment visibility

Revision ID: 8bea5bfceb27
Revises: 2e9d66c17dc1
Create Date: 2026-02-15 23:55:11.817815

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8bea5bfceb27"
down_revision: str | Sequence[str] | None = "2e9d66c17dc1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assessments",
        sa.Column("visibility", sa.String(length=50), server_default="private", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assessments", "visibility")
    # ### end Alembic commands ###
