"""add argument keys to target elements

Revision ID: 997b7707ca03
Revises: d5d4db4ad4ee
Create Date: 2026-03-25 13:00:44.440388

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "997b7707ca03"
down_revision: str | Sequence[str] | None = "d5d4db4ad4ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "target_elements",
        sa.Column("argument_keys", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("target_elements", "argument_keys")
    # ### end Alembic commands ###
