"""add code info to question templates

Revision ID: a6ed89ae3130
Revises: 997b7707ca03
Create Date: 2026-03-30 17:11:23.066350

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6ed89ae3130"
down_revision: str | Sequence[str] | None = "997b7707ca03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question_templates", sa.Column("code_info", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question_templates", "code_info")
    # ### end Alembic commands ###
