"""add one_time_tokens table for email verification

Revision ID: a8d9cc8336b7
Revises: 39176a2ce4db
Create Date: 2026-02-09 14:48:58.373248

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8d9cc8336b7"
down_revision: str | Sequence[str] | None = "39176a2ce4db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "one_time_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "token_type",
            sa.Enum("EMAIL_VERIFICATION", "PASSWORD_RESET", name="tokentype"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_one_time_tokens_token_hash"), "one_time_tokens", ["token_hash"], unique=True
    )
    op.create_index(
        op.f("ix_one_time_tokens_token_type"), "one_time_tokens", ["token_type"], unique=False
    )
    op.create_index(
        op.f("ix_one_time_tokens_user_id"), "one_time_tokens", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_one_time_tokens_user_id"), table_name="one_time_tokens")
    op.drop_index(op.f("ix_one_time_tokens_token_type"), table_name="one_time_tokens")
    op.drop_index(op.f("ix_one_time_tokens_token_hash"), table_name="one_time_tokens")
    op.drop_table("one_time_tokens")
    # ### end Alembic commands ###
