"""remove question many-to-many tables

Revision ID: ac775b2924f1
Revises: c0cc1cd462ef
Create Date: 2026-03-18 17:22:51.471711

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac775b2924f1"
down_revision: str | Sequence[str] | None = "c0cc1cd462ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questions", sa.Column("assessment_id", sa.Uuid(), nullable=True))
    op.add_column("questions", sa.Column("question_bank_id", sa.Uuid(), nullable=True))
    op.add_column("questions", sa.Column("order", sa.Integer(), nullable=True))

    # Migrate data from junction tables into questions columns
    op.execute(
        """
        UPDATE questions q
        SET assessment_id = aq.assessment_id,
            "order" = aq."order"
        FROM assessment_questions aq
        WHERE aq.question_id = q.id
        """
    )
    op.execute(
        """
        UPDATE questions q
        SET question_bank_id = qbq.question_bank_id
        FROM question_bank_questions qbq
        WHERE qbq.question_id = q.id
        """
    )

    op.drop_index(
        op.f("ix_question_bank_questions_question_bank_id"),
        table_name="question_bank_questions",
    )
    op.drop_index(
        op.f("ix_question_bank_questions_question_id"),
        table_name="question_bank_questions",
    )
    op.drop_table("question_bank_questions")
    op.drop_index(
        op.f("ix_assessment_questions_assessment_id"), table_name="assessment_questions"
    )
    op.drop_index(
        op.f("ix_assessment_questions_question_id"), table_name="assessment_questions"
    )
    op.drop_table("assessment_questions")
    op.create_index(
        op.f("ix_questions_assessment_id"), "questions", ["assessment_id"], unique=False
    )
    op.create_index(
        op.f("ix_questions_question_bank_id"),
        "questions",
        ["question_bank_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_question_assessment_order", "questions", ["assessment_id", "order"]
    )
    op.create_check_constraint(
        "ck_question_single_container",
        "questions",
        "assessment_id IS NULL OR question_bank_id IS NULL",
    )
    op.create_foreign_key(
        "fk_question_id_assessment_id",
        "questions",
        "assessments",
        ["assessment_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_question_id_qbank_id",
        "questions",
        "question_banks",
        ["question_bank_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_question_id_assessment_id", "questions", type_="foreignkey")
    op.drop_constraint("fk_question_id_qbank_id", "questions", type_="foreignkey")
    op.drop_constraint("ck_question_single_container", "questions", type_="check")
    op.drop_constraint("uq_question_assessment_order", "questions", type_="unique")
    op.drop_index(op.f("ix_questions_question_bank_id"), table_name="questions")
    op.drop_index(op.f("ix_questions_assessment_id"), table_name="questions")
    op.drop_column("questions", "order")
    op.drop_column("questions", "question_bank_id")
    op.drop_column("questions", "assessment_id")
    op.create_table(
        "assessment_questions",
        sa.Column("assessment_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("question_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("order", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "added_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("assessment_questions_assessment_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("assessment_questions_question_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("assessment_questions_pkey")),
        sa.UniqueConstraint(
            "assessment_id",
            "order",
            name=op.f("uq_assessment_question_order"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "assessment_id",
            "question_id",
            name=op.f("uq_assessment_question"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_assessment_questions_question_id"),
        "assessment_questions",
        ["question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_questions_assessment_id"),
        "assessment_questions",
        ["assessment_id"],
        unique=False,
    )
    op.create_table(
        "question_bank_questions",
        sa.Column("question_bank_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("question_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "added_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_bank_id"],
            ["question_banks.id"],
            name=op.f("question_bank_questions_question_bank_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("question_bank_questions_question_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("question_bank_questions_pkey")),
        sa.UniqueConstraint(
            "question_bank_id",
            "question_id",
            name=op.f("uq_question_bank_question"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_question_bank_questions_question_id"),
        "question_bank_questions",
        ["question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_bank_questions_question_bank_id"),
        "question_bank_questions",
        ["question_bank_id"],
        unique=False,
    )
    # ### end Alembic commands ###
