"""copy on link questions

Revision ID: c0cc1cd462ef
Revises: 8a6af857e1df
Create Date: 2026-03-17 19:41:53.162717

"""

import uuid
from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0cc1cd462ef"
down_revision: str | Sequence[str] | None = "8a6af857e1df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None: # noqa: C901
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions", sa.Column("linked_from_question_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        op.f("ix_questions_linked_from_question_id"),
        "questions",
        ["linked_from_question_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_questions_linked_from_question_id",
        "questions",
        "questions",
        ["linked_from_question_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###

    # Data migration: for questions shared across multiple containers, create
    # independent copies so each container has its own question instance.
    conn = op.get_bind()

    # Reflect needed tables
    meta = sa.MetaData()
    questions = sa.Table("questions", meta, autoload_with=conn)
    aq = sa.Table("assessment_questions", meta, autoload_with=conn)
    qbq = sa.Table("question_bank_questions", meta, autoload_with=conn)
    mcq_data = sa.Table("mcq_data", meta, autoload_with=conn)
    mrq_data = sa.Table("mrq_data", meta, autoload_with=conn)
    short_answer_data = sa.Table("short_answer_data", meta, autoload_with=conn)

    # Find all question IDs that appear in more than one container (across
    # assessment_questions and question_bank_questions combined).
    aq_rows = conn.execute(
        sa.select(aq.c.question_id, aq.c.id, sa.literal("assessment").label("source"))
    ).fetchall()
    qbq_rows = conn.execute(
        sa.select(
            qbq.c.question_id, qbq.c.id, sa.literal("question_bank").label("source")
        )
    ).fetchall()

    # Group all container associations by question_id
    from collections import defaultdict

    assocs_by_question: dict = defaultdict(list)
    for row in aq_rows:
        assocs_by_question[row.question_id].append(("assessment", row.id))
    for row in qbq_rows:
        assocs_by_question[row.question_id].append(("question_bank", row.id))

    now = datetime.now(UTC)

    for question_id, assocs in assocs_by_question.items():
        if len(assocs) <= 1:
            continue

        # Fetch the original question
        q_row = conn.execute(
            sa.select(questions).where(questions.c.id == question_id)
        ).fetchone()
        if q_row is None:
            continue

        # Keep the first association pointing to the original question.
        # For each subsequent association, create a copy and re-point the junction row.
        for source_type, assoc_id in assocs[1:]:
            new_id = uuid.uuid4()
            conn.execute(
                questions.insert().values(
                    id=new_id,
                    owner_id=q_row.owner_id,
                    template_id=q_row.template_id,
                    linked_from_question_id=None,
                    question_type=q_row.question_type,
                    question_text=q_row.question_text,
                    created_at=now,
                    updated_at=now,
                    deleted_at=q_row.deleted_at,
                )
            )

            # Copy type-specific data
            if q_row.question_type == "mcq":
                mcq_row = conn.execute(
                    sa.select(mcq_data).where(mcq_data.c.question_id == question_id)
                ).fetchone()
                if mcq_row:
                    conn.execute(
                        mcq_data.insert().values(
                            question_id=new_id,
                            options=mcq_row.options,
                            correct_index=mcq_row.correct_index,
                        )
                    )
            elif q_row.question_type == "mrq":
                mrq_row = conn.execute(
                    sa.select(mrq_data).where(mrq_data.c.question_id == question_id)
                ).fetchone()
                if mrq_row:
                    conn.execute(
                        mrq_data.insert().values(
                            question_id=new_id,
                            options=mrq_row.options,
                            correct_indices=mrq_row.correct_indices,
                        )
                    )
            elif q_row.question_type == "short_answer":
                sa_row = conn.execute(
                    sa.select(short_answer_data).where(
                        short_answer_data.c.question_id == question_id
                    )
                ).fetchone()
                if sa_row:
                    conn.execute(
                        short_answer_data.insert().values(
                            question_id=new_id,
                            correct_answer=sa_row.correct_answer,
                        )
                    )

            # Re-point the junction row to the copy
            if source_type == "assessment":
                conn.execute(
                    aq.update().where(aq.c.id == assoc_id).values(question_id=new_id)
                )
            else:
                conn.execute(
                    qbq.update().where(qbq.c.id == assoc_id).values(question_id=new_id)
                )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_questions_linked_from_question_id", "questions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_questions_linked_from_question_id"), table_name="questions")
    op.drop_column("questions", "linked_from_question_id")
    # ### end Alembic commands ###
