"""add question data tables

Revision ID: c31d5bcd841c
Revises: a8d9cc8336b7
Create Date: 2026-02-12 15:35:20.000413

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c31d5bcd841c"
down_revision: str | Sequence[str] | None = "a8d9cc8336b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcq_data",
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("options", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("correct_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("question_id"),
    )
    op.create_table(
        "mrq_data",
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("options", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("correct_indices", sa.ARRAY(sa.Integer()), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("question_id"),
    )
    op.create_table(
        "short_answer_data",
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("correct_answer", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("question_id"),
    )
    op.create_check_constraint(
        "valid_question_type",
        "questions",
        "question_type IN ('mcq', 'mrq', 'short_answer')",
    )
    op.drop_column("questions", "additional_data")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("valid_question_type", "questions", type_="check")
    op.add_column(
        "questions",
        sa.Column(
            "additional_data",
            postgresql.JSON(astext_type=sa.Text()),
            server_default=sa.text("'{}'::json"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("short_answer_data")
    op.drop_table("mrq_data")
    op.drop_table("mcq_data")
    # ### end Alembic commands ###
