"""add question bank

Revision ID: ca836cc22081
Revises: 79dc1a47e5c6
Create Date: 2026-02-14 16:16:27.786868

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca836cc22081"
down_revision: str | Sequence[str] | None = "79dc1a47e5c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_banks",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("folder_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["folder_id"], ["folders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_banks_folder_id"), "question_banks", ["folder_id"], unique=False
    )
    op.create_index(
        op.f("ix_question_banks_owner_id"), "question_banks", ["owner_id"], unique=False
    )
    op.create_table(
        "question_bank_questions",
        sa.Column("question_bank_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["question_bank_id"], ["question_banks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("question_bank_id", "question_id", name="uq_question_bank_question"),
    )
    op.create_index(
        op.f("ix_question_bank_questions_question_bank_id"),
        "question_bank_questions",
        ["question_bank_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_bank_questions_question_id"),
        "question_bank_questions",
        ["question_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_question_bank_questions_question_id"), table_name="question_bank_questions"
    )
    op.drop_index(
        op.f("ix_question_bank_questions_question_bank_id"), table_name="question_bank_questions"
    )
    op.drop_table("question_bank_questions")
    op.drop_index(op.f("ix_question_banks_owner_id"), table_name="question_banks")
    op.drop_index(op.f("ix_question_banks_folder_id"), table_name="question_banks")
    op.drop_table("question_banks")
    # ### end Alembic commands ###
