"""add input data config

Revision ID: fef2e085b62e
Revises: 5bd365832755
Create Date: 2026-03-09 16:09:46.306924

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fef2e085b62e"
down_revision: str | Sequence[str] | None = "5bd365832755"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("question_templates", sa.Column("input_data_config", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question_templates", "input_data_config")
    # ### end Alembic commands ###
